// scripts/training.rs ~=#######D]======A===r===c====M===o===o===n=====<Lord[SCRIPTS]Xyn>=====S===t===u===d===i===o===s======[R|$>
// scripts/training.rs ~=#######D]======A===r===c====M===o===o===n=====<Lord[SCRIPTS]Xyn>=====S===t===u===d===i===o===s======[R|$>
// scripts/training.rs ~=#######D]======A===r===c====M===o===o===n=====<Lord[SCRIPTS]Xyn>=====S===t===u===d===i===o===s======[R|$>
// scripts/training.rs ~=#######D]======A===r===c====M===o===o===n=====<Lord[SCRIPTS]Xyn>=====S===t===u===d===i===o===s======[R|$>
// scripts/training.rs ~=#######D]======A===r===c====M===o===o===n=====<Lord[SCRIPTS]Xyn>=====S===t===u===d===i===o===s======[R|$>
// scripts/training.rs ~=#######D]======A===r===c====M===o===o===n=====<Lord[SCRIPTS]Xyn>=====S===t===u===d===i===o===s======[R|$>
// scripts/training.rs ~=#######D]======A===r===c====M===o===o===n=====<Lord[SCRIPTS]Xyn>=====S===t===u===d===i===o===s======[R|$>
// scripts/training.rs ~=#######D]======A===r===c====M===o===o===n=====<Lord[SCRIPTS]Xyn>=====S===t===u===d===i===o===s======[R|$>
// scripts/training.rs ~=#######D]======A===r===c====M===o===o===n=====<Lord[SCRIPTS]Xyn>=====S===t===u===d===i===o===s======[R|$>
// scripts/training.rs ~=#######D]======A===r===c====M===o===o===n=====<Lord[SCRIPTS]Xyn>=====S===t===u===d===i===o===s======[R|$>
// scripts/training.rs ~=#######D]======A===r===c====M===o===o===n=====<Lord[SCRIPTS]Xyn>=====S===t===u===d===i===o===s======[R|$>
// scripts/training.rs ~=#######D]======A===r===c====M===o===o===n=====<Lord[SCRIPTS]Xyn>=====S===t===u===d===i===o===s======[R|$>
// scripts/training.rs ~=#######D]======A===r===c====M===o===o===n=====<Lord[SCRIPTS]Xyn>=====S===t===u===d===i===o===s======[R|$>